phi-4:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: microsoft/phi-4
    sparsity_config: "./config/cats/ideal/0.9_gen.yaml"
    sp_ideal: True
    trace_dir: "./alpaca_eval/results/phi-4/cats/0.9_ideal"
  fn_completions: huggingface_local_completions
  pretty_name: phi_cats_90_ideal
  prompt_template: phi-4/prompt.txt