trace_base_dir: "./DATA/user/countdown"
state: "ideal" # or "prac"
method: "cats" # or "dejavu" or "d-countdown" or "m-countdown"
gen: False
sparsity_ratio: 0.8
prior_dataset: 'Eval' # Only used for lm-eval