Llama-3.1-8B-Instruct:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    sparsity_config: "./config/d-countdown/prac/0.8_gen.yaml"
    sp_ideal: False
    predictor_dir: "./results/countdown_train/meta-llama_Meta-Llama-3.1-8B-Instruct/d-countdown/512/0.8/classification/0109145343"
    adjust_threshold: -1.0
    trace_dir: "./alpaca_eval/results/Llama-3.1-8B-Instruct/d-countdown/0.8_pred"
  fn_completions: huggingface_local_completions
  pretty_name: llama_d-countdown_80_pred
  prompt_template: Llama-3.1-8B-Instruct/prompt.txt