gemma-2-9b-it:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: google/gemma-2-9b-it
    sparsity_config: "./config/m-countdown/ideal/0.9_gen.yaml"
    sp_ideal: True
    trace_dir: "./alpaca_eval/results/gemma-2-9b-it/m-countdown/0.9_ideal"
  fn_completions: huggingface_local_completions
  pretty_name: gemma-2-9b-it_dense
  prompt_template: gemma-2-9b-it/prompt.txt
