trace_base_dir: "./DATA/user/countdown"
state: "prac" # or "ideal"
method: "m-countdown" # or "dejavu" or "d-countdown" or "m-countdown"
gen: False
sparsity_ratio: 0.8
prior_dataset: 'Train' # Only used for lm-eval
