trace_base_dir: "./DATA/user/countdown"
state: "ideal" # or "prac"
method: "trace_only" # or "dejavu" or "d-countdown" or "m-countdown" or "cats"
gen: False
sparsity_ratio: 0
prior_dataset: 'Train' # Only used for lm-eval
