Llama-3.1-8B-Instruct:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    trace_dir: "./alpaca_eval/results/Llama-3.1-8B-Instruct/dense"
  fn_completions: huggingface_local_completions
  pretty_name: llama_dense
  prompt_template: Llama-3.1-8B-Instruct/prompt.txt