Qwen2.5-14B-Instruct:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: Qwen/Qwen2.5-14B-Instruct
    sparsity_config: "./config/cats/prac/0.7_gen.yaml"
    sp_ideal: False
    predictor_dir: "./DATA/user/countdown/Qwen__Qwen2.5-14B-Instruct/cats/ideal/0.7"
    trace_dir: "./alpaca_eval/results/Qwen2.5-14B-Instruct/cats/0.7_pred"
  fn_completions: huggingface_local_completions
  pretty_name: qwen_cats_70_pred
  prompt_template: Qwen2.5-14B-Instruct/prompt.txt