Llama-3.1-8B-Instruct:
  completions_kwargs:
    batch_size: 4
    do_sample: False
    max_new_tokens: 2048
    model_kwargs:
      torch_dtype: float32
      device_map: auto
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
    sparsity_config: "./config/m-countdown/prac/0.7_gen.yaml"
    sp_ideal: False
    predictor_dir: "./DATA/user/countdown/meta-llama__Meta-Llama-3.1-8B-Instruct/m-countdown/ideal/0.7"
    trace_dir: "./alpaca_eval/results/Llama-3.1-8B-Instruct/m-countdown/0.7_pred"
  fn_completions: huggingface_local_completions
  pretty_name: llama_m-countdown_70_pred
  prompt_template: Llama-3.1-8B-Instruct/prompt.txt

  